apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: container-mirror-image-mutating
webhooks:
  - name: image.mirror.container-mirror.aws
    failurePolicy: Ignore
    sideEffects: None
    admissionReviewVersions: ["v1"]
    clientConfig:
      url: REPLACE_WITH_API_GATEWAY_URL
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]

